// // INSERT INTO products ( name, type, price, stock, discount, img, des, rating, new, href, detail, nutrition, origin)
// // VALUES
// // ('Orange', 'fresh', 3, 20, 0, '/fruits/orange.jpg', 'An orange', 4.9, true, '/store/orange', 'Our freshly picked oranges are bursting with juicy, sun-kissed flavor. Grown with care and harvested at their peak, these oranges are a delicious source of Vitamin C and a perfect healthy snack.','Vitamin A, B', 'Thailand'),
// // ('Apple', 'fresh', 3, 20, 0.2, '/fruits/apple.jpg', 'An apple', 4.8, false, '/store/apple', 'Reach for a crunchy, refreshing apple – a timeless healthy choice packed with flavor and essential nutrients. Grown with care and picked at their peak, our apples are a delicious on-the-go option or a delightful addition to any meal., ','Vitamin B, C', 'Indonesia'),
// // ('Giwi', 'fresh', 5, 20, 0, '/fruits/giwi.jpg', 'A giwi', 5, false, '/store/giwi', 'Experience the delightful kiwi! This captivating fruit boasts a vibrant green flesh and a fuzzy brown exterior, offering a fun and unique eating experience. But don"t be fooled by the fuzz, the inside is packed with juicy sweetness and a refreshing tang., ','Vitamin C', 'Thailand'),
// // ('Mango', 'fresh', 4, 20, 0.1, '/fruits/mango.jpg', 'A mango', 5, false, '/store/mango', 'Indulge in the natural sweetness of our mangoes! These luscious fruits are a delicious treat on their own, perfect for satisfying your sweet tooth the healthy way. They can also be diced into salads, blended into smoothies, or dried for a chewy and flavorful snack., ','Vitamin A, C', 'Bali'),
// // ('Strawberry', 'fresh', 6, 20, 0, '/fruits/strawberry.jpg', 'A strawberry', 4.8, true, '/store/strawberry', 'Bursting with juicy flavor and a vibrant red hue, our strawberries are a taste of sunshine captured in a fruit. Freshly picked at peak ripeness, they offer the perfect balance of sweetness and tartness for a truly delightful snack., ','Vitamin C', 'Indonesia'),
// // ('Watermelon', 'fresh', 5, 20, 0.1, '/fruits/watermelon.jpg', 'A watermelon', 4.7, false, '/store/watermelon', 'Beat the heat with nature"s candy - our perfectly ripe watermelons! This juicy fruit boasts a refreshing burst of sweetness with every bite, offering the ultimate summertime hydration.', 'Vitamin A', 'Bali'),
// // ('Peach', 'fresh', 5, 20, 0, '/fruits/peach.jpg', 'A watermelon', 4.5, false, '/store/peach', ' Sink your teeth into the juicy perfection of our sun-ripened peaches! Their vibrant golden flesh boasts a burst of sweetness with a touch of tartness, offering a delightful taste of summer in every bite., ','Vitamin A, C', 'Thailand'),
// // ('Grape', 'fresh', 4, 20, 0.2, '/fruits/grape.jpg', 'A grape', 5, false, '/store/grape', 'Dive into a world of juicy goodness with our selection of grapes! From the classic dark red globes to the refreshing green seedless varieties, we offer a flavor and color for every taste bud. Explore the delightful world of grapes!', 'Vitamin A, B, C', 'Indonesia'),
// // ('Banana', 'fresh', 2, 20, 0, '/fruits/banana.jpg', 'Banana', 4.9, true, '/store/banana', 'Grab a banana and fuel your day with the natural energy of sunshine! Packed with potassium and carbohydrates, this portable and delicious fruit is the perfect way to keep your energy levels up, no matter where you are.', 'Vitamin A, Magnesium', 'Bali'),
// // ('Blueberry', 'fresh', 6, 20, 0.1, '/fruits/blueberry.jpg', 'Blueberries', 4.7, false, '/store/blueberry', 'Unleash a burst of flavor with our plump and fresh blueberries! These vibrant little gems boast a beautiful indigo hue and a burst of sweet and tart flavor, offering a taste of summer in every bite.', 'Vitamin C', 'Thailand'),
// // ('Papaya', 'fresh', 4, 20, 0, '/fruits/papaya.jpg', 'papaya', 4.8, false, '/store/papaya', 'Experience the luxurious texture of our papayas! Their smooth and creamy flesh melts in your mouth, offering a delightful contrast to the tiny black seeds that add a pleasant crunch.', 'Vitamin A, C', 'Indonesia'),
// // ('Raspberry', 'fresh', 5, 20, 0.2, '/fruits/raspberry.jpg', 'a bowl of raspberries', 4.6, false, '/store/raspberry', 'Indulge in the delightful burst of flavor with our plump and juicy raspberries! These delicate jewels boast a vibrant red hue and a sweet, tangy taste that is both refreshing and luxurious.', 'Vitamin C', 'Bali'),
// // ('Durian', 'fresh', 8, 20, 0, '/fruits/durian.jpg', 'a durian', 5, true, '/store/durian', 'Embrace the adventure with durian, the fruit that dares to be different! This Southeast Asian delicacy boasts a creamy, custard-like texture and a complex flavor profile that"s both sweet and savory, with hints of onion, garlic, and caramel. Are you brave enough to try the king of fruits?', 'Vitamin A, C', 'Thailand'),
// // ('Dragonfruit', 'fresh', 5, 20, 0.1, '/fruits/dragonfruit.jpg', 'a dragonfruit', 4.9, false, '/store/dragonfruit', 'Unleash the vibrant beauty of dragonfruit! This exotic fruit boasts a stunning pink or white exterior with vibrant green scales, offering a visual feast before you even take a bite. Inside, the sweet and refreshing flesh awaits, making dragonfruit a truly delightful experience.', 'Vitamin A, C', 'Indonesia'),
// // ('Pineapple', 'fresh', 3, 20, 0, '/fruits/pineapple.jpg', 'a pineapple', 4.7, false, '/store/pineapple', 'Embrace the taste of summer with our perfectly ripe pineapples! Bursting with juicy sweetness and a touch of tang, these tropical treats offer a taste of paradise in every bite.', 'Vitamin C', 'Bali'),
// // ('Raisin', 'dried', 3, 20, 0.2, '/fruits/raisin.jpg', 'a bowl of raisin', 4.9, false, '/store/raisin', ' Packed with concentrated sunshine, our raisins offer a burst of natural sweetness in every bite! These plump and chewy dried grapes are a delicious and healthy way to satisfy your sweet tooth on the go.', 'Vitamin A, C', 'Thailand'),
// // ('Prune', 'dried', 4, 20, 0, '/fruits/prune.jpg', 'a bowl of prune', 4.8, true, '/store/prune', 'Indulge in the naturally sweet and chewy goodness of our prunes! These dried plums offer a delicious way to add fiber, vitamins, and antioxidants to your diet. They"re a perfect snack for satisfying your sweet tooth while supporting your well-being.', 'Vitamin C', 'Bali'),
// // ('Fig', 'dried', 5, 20, 0.1, '/fruits/fig.jpg', 'a bowl of fig', 4.6, false, '/store/fig', 'Indulge in the luxurious texture and flavor of our perfectly ripe figs! These jewel-toned fruits boast a soft, jammy interior with a delightful crunch from the tiny seeds, offering a unique and satisfying taste sensation in every bite.', 'Vitamin C', 'Indonesia'),
// // ('Apricot', 'dried', 3, 20, 0, '/fruits/apricot.jpg', 'a bowl of apricot', 4.8, false, '/store/apricot', 'Capture the essence of summer with our perfectly ripe apricots! These golden gems boast a burst of sweet, tangy flavor with a hint of citrus, offering a taste of sunshine in every delicious bite.', 'Vitamin C', 'Thailand'),
// // ('Date', 'dried', 3, 20, 0.2, '/fruits/date.jpg', 'a bowl of date', 4.8, false, '/store/date', 'Packed with fiber, natural sugars, and essential minerals, dates offer a delicious and sustained energy boost. Enjoy them as a pre-workout snack or a healthy afternoon pick-me-up to power through your day.', 'Vitamin C', 'Indonesia'),
// // ('Walnut', 'dried', 5, 20, 0, '/fruits/walnut.jpg', 'a bowl of walnut', 4.9, true, '/store/walnut', 'Experience the delightful contrast of our walnuts! Their smooth, buttery kernels offer a decadent richness, while the hint of a satisfying crunch from the thin shell adds a touch of textural intrigue. Indulge in the luxurious taste of walnuts - nature"s gourmet nut.', 'Magnesium, Calcium', 'Bali'),
// // ('Sunflower Seed', 'dried', 5, 20, 0.1, '/fruits/sunflower-seed.jpg', 'a bowl of sunflower seed', 4.9, false, '/store/sunflower seed', 'Sunflower seeds are packed with healthy fats, protein, and fiber, making them a delicious and nutritious snack option. They"re a natural source of Vitamin E, essential for healthy skin and overall well-being.', 'Magnesium', 'Thailand'),
// // ('Almond', 'dried', 4, 20, 0, '/fruits/almond.jpg', 'a bowl of almond', 4.8, false, '/store/almond', 'Almonds are a treasure trove of essential nutrients! Packed with protein, healthy fats, fiber, and Vitamin E, they offer a delicious way to support your heart health, cognitive function, and overall well-being.', 'Magnesium', 'Indonesia'),
// // ('Cashew Nut', 'dried', 5, 20, 0.2, '/fruits/cashew-nut.jpg', 'a bowl of cashew nut', 4.9, false, '/store/cashew nut', 'Experience the delightful creaminess of our premium cashews! These versatile nuts boast a smooth, buttery texture and a hint of sweetness, making them a luxurious and satisfying snack option that can be enjoyed on their own or incorporated into a variety of dishes.', 'Magnesium', 'Bali'),
// // ('Macademia', 'dried', 6, 20, 0, '/fruits/macademia.jpg', 'a bowl of macademia', 4.8, true, '/store/macademia', 'Experience the luxurious taste and texture of our premium macadamia nuts!  These Australian treasures boast a buttery richness with a satisfyingly smooth and slightly crunchy texture, making them a gourmet snack fit for royalty.', 'Magnesium', 'Thailand')

// INSERT INTO product (id, name, type, price, stock, discount, des, rating, new, detail_id)
// VALUES
// (1, 'Orange', 'fresh', 3, 20, 0, 'An orange', 4.9, true, 1),
// (2, 'Apple', 'fresh', 3, 20, 0.2, 'An apple', 4.8, false, 2),
// (3, 'Giwi', 'fresh', 5, 20, 0, 'A giwi', 5, false, 3),
// (4, 'Mango', 'fresh', 4, 20, 0.1, 'A mango', 5, false, 4),
// (5, 'Strawberry', 'fresh', 6, 20, 0, 'A strawberry', 4.8, true, 5),
// (6, 'Watermelon', 'fresh', 5, 20, 0.1, 'A watermelon', 4.7, false, 6),
// (7, 'Peach', 'fresh', 5, 20, 0, 'A watermelon', 4.5, false, 7),
// (8, 'Grape', 'fresh', 4, 20, 0.2, 'A grape', 5, false, 8),
// (9, 'Banana', 'fresh', 2, 20, 0, 'Banana', 4.9, true, 9),
// (10, 'Blueberry', 'fresh', 6, 20, 0.1, 'Blueberries', 4.7, false, 10),
// (11, 'Papaya', 'fresh', 4, 20, 0, 'papaya', 4.8, false, 11),
// (12, 'Raspberry', 'fresh', 5, 20, 0.2, 'a bowl of raspberries', 4.6, false, 12),
// (13, 'Durian', 'fresh', 8, 20, 0, 'a durian', 5, true, 13),
// (14, 'Dragonfruit', 'fresh', 5, 20, 0.1, 'a dragonfruit', 4.9, false, 14),
// (15, 'Pineapple', 'fresh', 3, 20, 0, 'a pineapple', 4.7, false, 15),
// (16, 'Raisin', 'dried', 3, 20, 0.2, 'a bowl of raisin', 4.9, false, 16),
// (17, 'Prune', 'dried', 4, 20, 0, 'a bowl of prune', 4.8, true, 17),
// (18, 'Fig', 'dried', 5, 20, 0.1, 'a bowl of fig', 4.6, false, 18),
// (19, 'Apricot', 'dried', 3, 20, 0, 'a bowl of apricot', 4.8, false, 19),
// (20, 'Date', 'dried', 3, 20, 0.2, 'a bowl of date', 4.8, false, 20),
// (21, 'Walnut', 'dried', 5, 20, 0, 'a bowl of walnut', 4.9, true, 21),
// (22, 'Sunflower Seed', 'dried', 5, 20, 0.1, 'a bowl of sunflower seed', 4.9, false, 22),
// (23, 'Almond', 'dried', 4, 20, 0, 'a bowl of almond', 4.8, false, 23),
// (24, 'Cashew Nut', 'dried', 5, 20, 0.2, 'a bowl of cashew nut', 4.9, false, 24),
// (25, 'Macademia', 'dried', 6, 20, 0, 'a bowl of macademia', 4.8, true, 25)

// INSERT INTO product (id, name, type, price, stock, discount, des, rating, new)
// VALUES
// (1, 'Orange', 'fresh', 3, 3, 0, 'An orange', 4.9, true),
// (2, 'Apple', 'fresh', 3, 28, 0.2, 'An apple', 4.8, false),
// (3, 'Giwi', 'fresh', 5, 15, 0, 'A giwi', 5, false),
// (4, 'Mango', 'fresh', 4, 1, 0.1, 'A mango', 5, false),
// (5, 'Strawberry', 'fresh', 6, 12, 0, 'A strawberry', 4.8, true),
// (6, 'Watermelon', 'fresh', 5, 15, 0.1, 'A watermelon', 4.7, false),
// (7, 'Peach', 'fresh', 5, 4, 0, 'A watermelon', 4.5, false),
// (8, 'Grape', 'fresh', 4, 8, 0.2, 'A grape', 5, false),
// (9, 'Banana', 'fresh', 2, 11, 0, 'Banana', 4.9, true),
// (10, 'Blueberry', 'fresh', 6, 13, 0.1, 'Blueberries', 4.7, false),
// (11, 'Papaya', 'fresh', 4,14, 0, 'papaya', 4.8, false),
// (12, 'Raspberry', 'fresh', 5, 3, 0.2, 'a bowl of raspberries', 4.6, false),
// (13, 'Durian', 'fresh', 8, 9, 0, 'a durian', 5, true),
// (14, 'Dragonfruit', 'fresh', 5, 22, 0.1, 'a dragonfruit', 4.9, false),
// (15, 'Pineapple', 'fresh', 3, 20, 0, 'a pineapple', 4.7, false),
// (16, 'Raisin', 'dried', 3, 19, 0.2, 'a bowl of raisin', 4.9, false),
// (17, 'Prune', 'dried', 4, 13, 0, 'a bowl of prune', 4.8, true),
// (18, 'Fig', 'dried', 5, 17, 0.1, 'a bowl of fig', 4.6, false),
// (19, 'Apricot', 'dried', 3, 31, 0, 'a bowl of apricot', 4.8, false),
// (20, 'Date', 'dried', 3, 13, 0.2, 'a bowl of date', 4.8, false),
// (21, 'Walnut', 'dried', 5, 23, 0, 'a bowl of walnut', 4.9, true),
// (22, 'Sunflower Seed', 'dried', 5, 32, 0.1, 'a bowl of sunflower seed', 4.9, false),
// (23, 'Almond', 'dried', 4, 4, 0, 'a bowl of almond', 4.8, false),
// (24, 'Cashew Nut', 'dried', 5, 2, 0.2, 'a bowl of cashew nut', 4.9, false),
// (25, 'Macademia', 'dried', 6, 5, 0, 'a bowl of macademia', 4.8, true)


// INSERT INTO product_detail ( id, detail, nutrition, origin)
// VALUES
// (1, 'Our freshly picked oranges are bursting with juicy, sun-kissed flavor. Grown with care and harvested at their peak, these oranges are a delicious source of Vitamin C and a perfect healthy snack.','Vitamin A, B', 'Thailand'),
// (2, 'Reach for a crunchy, refreshing apple – a timeless healthy choice packed with flavor and essential nutrients. Grown with care and picked at their peak, our apples are a delicious on-the-go option or a delightful addition to any meal., ','Vitamin B, C', 'Indonesia'),
// (3, 'Experience the delightful kiwi! This captivating fruit boasts a vibrant green flesh and a fuzzy brown exterior, offering a fun and unique eating experience. But don"t be fooled by the fuzz, the inside is packed with juicy sweetness and a refreshing tang., ','Vitamin C', 'Thailand'),
// (4,'Indulge in the natural sweetness of our mangoes! These luscious fruits are a delicious treat on their own, perfect for satisfying your sweet tooth the healthy way. They can also be diced into salads, blended into smoothies, or dried for a chewy and flavorful snack., ','Vitamin A, C', 'Bali'),
// (5,'Bursting with juicy flavor and a vibrant red hue, our strawberries are a taste of sunshine captured in a fruit. Freshly picked at peak ripeness, they offer the perfect balance of sweetness and tartness for a truly delightful snack., ','Vitamin C', 'Indonesia'),
// (6,'Beat the heat with nature"s candy - our perfectly ripe watermelons! This juicy fruit boasts a refreshing burst of sweetness with every bite, offering the ultimate summertime hydration.', 'Vitamin A', 'Bali'),
// (7,'Sink your teeth into the juicy perfection of our sun-ripened peaches! Their vibrant golden flesh boasts a burst of sweetness with a touch of tartness, offering a delightful taste of summer in every bite., ','Vitamin A, C', 'Thailand'),
// (8,'Dive into a world of juicy goodness with our selection of grapes! From the classic dark red globes to the refreshing green seedless varieties, we offer a flavor and color for every taste bud. Explore the delightful world of grapes!', 'Vitamin A, B, C', 'Indonesia'),
// (9,'Grab a banana and fuel your day with the natural energy of sunshine! Packed with potassium and carbohydrates, this portable and delicious fruit is the perfect way to keep your energy levels up, no matter where you are.', 'Vitamin A, Magnesium', 'Bali'),
// (10,'Unleash a burst of flavor with our plump and fresh blueberries! These vibrant little gems boast a beautiful indigo hue and a burst of sweet and tart flavor, offering a taste of summer in every bite.', 'Vitamin C', 'Thailand'),
// (11,'Experience the luxurious texture of our papayas! Their smooth and creamy flesh melts in your mouth, offering a delightful contrast to the tiny black seeds that add a pleasant crunch.', 'Vitamin A, C', 'Indonesia'),
// (12,'Indulge in the delightful burst of flavor with our plump and juicy raspberries! These delicate jewels boast a vibrant red hue and a sweet, tangy taste that is both refreshing and luxurious.', 'Vitamin C', 'Bali'),
// (13,'Embrace the adventure with durian, the fruit that dares to be different! This Southeast Asian delicacy boasts a creamy, custard-like texture and a complex flavor profile that"s both sweet and savory, with hints of onion, garlic, and caramel. Are you brave enough to try the king of fruits?', 'Vitamin A, C', 'Thailand'),
// (14,'Unleash the vibrant beauty of dragonfruit! This exotic fruit boasts a stunning pink or white exterior with vibrant green scales, offering a visual feast before you even take a bite. Inside, the sweet and refreshing flesh awaits, making dragonfruit a truly delightful experience.', 'Vitamin A, C', 'Indonesia'),
// (15,'Embrace the taste of summer with our perfectly ripe pineapples! Bursting with juicy sweetness and a touch of tang, these tropical treats offer a taste of paradise in every bite.', 'Vitamin C', 'Bali'),
// (16,'Packed with concentrated sunshine, our raisins offer a burst of natural sweetness in every bite! These plump and chewy dried grapes are a delicious and healthy way to satisfy your sweet tooth on the go.', 'Vitamin A, C', 'Thailand'),
// (17,'Indulge in the naturally sweet and chewy goodness of our prunes! These dried plums offer a delicious way to add fiber, vitamins, and antioxidants to your diet. They"re a perfect snack for satisfying your sweet tooth while supporting your well-being.', 'Vitamin C', 'Bali'),
// (18,'Indulge in the luxurious texture and flavor of our perfectly ripe figs! These jewel-toned fruits boast a soft, jammy interior with a delightful crunch from the tiny seeds, offering a unique and satisfying taste sensation in every bite.', 'Vitamin C', 'Indonesia'),
// (19,'Capture the essence of summer with our perfectly ripe apricots! These golden gems boast a burst of sweet, tangy flavor with a hint of citrus, offering a taste of sunshine in every delicious bite.', 'Vitamin C', 'Thailand'),
// (20,'Packed with fiber, natural sugars, and essential minerals, dates offer a delicious and sustained energy boost. Enjoy them as a pre-workout snack or a healthy afternoon pick-me-up to power through your day.', 'Vitamin C', 'Indonesia'),
// (21,'Experience the delightful contrast of our walnuts! Their smooth, buttery kernels offer a decadent richness, while the hint of a satisfying crunch from the thin shell adds a touch of textural intrigue. Indulge in the luxurious taste of walnuts - nature"s gourmet nut.', 'Magnesium, Calcium', 'Bali'),
// (22,'Sunflower seeds are packed with healthy fats, protein, and fiber, making them a delicious and nutritious snack option. They"re a natural source of Vitamin E, essential for healthy skin and overall well-being.', 'Magnesium', 'Thailand'),
// (23,'Almonds are a treasure trove of essential nutrients! Packed with protein, healthy fats, fiber, and Vitamin E, they offer a delicious way to support your heart health, cognitive function, and overall well-being.', 'Magnesium', 'Indonesia'),
// (24,'Experience the delightful creaminess of our premium cashews! These versatile nuts boast a smooth, buttery texture and a hint of sweetness, making them a luxurious and satisfying snack option that can be enjoyed on their own or incorporated into a variety of dishes.', 'Magnesium', 'Bali'),
// (25,'Experience the luxurious taste and texture of our premium macadamia nuts!  These Australian treasures boast a buttery richness with a satisfyingly smooth and slightly crunchy texture, making them a gourmet snack fit for royalty.', 'Magnesium', 'Thailand')

// INSERT INTO users (id, username, amount)
// VALUES
// (1, 'Kanissorn', 54.25),
// (2, 'Sinramon', 127.50),
// (3, 'Danaisate', 15),
// (4, 'Pheranat', 325),
// (5, 'Polawat', 45),
// (6, 'Kunanon', 78.75),
// (7, 'Ditsamon', 53.25),
// (8, 'Sittidet', 150.50)